/** Theme source of truth. Values below preserve the original Plum design exactly.
 * Add presets or edit tokens here; layout and components consume CSS variables.
 * Hue rotates brand colors together. Semantic feedback colors stay fixed.
 */
export const themeConfig = {
  baseHue: 270,
  defaultHue: 270,
  storageKey: 'vacation-window-appearance-v1',
  presets: [
    { name: 'Plum', hue: 270 },
    { name: 'Ocean', hue: 215 },
    { name: 'Forest', hue: 145 },
    { name: 'Terracotta', hue: 25 },
    { name: 'Rose', hue: 335 },
  ],
  fixedTokens: [
    'paper',
    'warm-accent',
    'warm-strong',
    'success',
    'success-bg',
    'danger',
    'danger-bg',
    'sun-ink',
    'header-glass',
    'status-pending',
    'status-ready',
    'status-glow',
    'glass-border',
    'assistant-glass',
    'neutral-day',
    'danger-border',
    'success-border',
    'blocked-stripe',
    'blocked-surface',
    'scene-sun',
    'scene-sky-end',
  ],
  colors: {
    ink: '#292937',
    'ink-soft': '#686877',
    paper: '#fff',
    canvas: '#f8f8fb',
    line: '#e5e4ed',
    border: '#e5e4ed',
    accent: '#51436d',
    'accent-hover': '#403454',
    'surface-selected': '#eee9f8',
    'brand-highlight': '#6d558c',
    'brand-ink': '#51436d',
    'focus-ring': '#695286',
    'surface-emphasis': '#e6def2',
    'surface-tint': '#f2eef8',
    'warm-accent': '#c76141',
    'warm-strong': '#a3442b',
    success: '#2f6757',
    'success-bg': '#eef6f0',
    danger: '#a23932',
    'danger-bg': '#fff0eb',
    'hover-border': '#b3a6c8',
    'pressed-shadow': '#51436d22',
    'note-start': '#f6f2fc',
    'note-end': '#faf9fc',
    'sun-ink': '#a06b42',
    'header-glass': '#ffffffa6',
    'muted-decoration': '#a5a0b1',
    'status-pending': '#ad792a',
    'status-ready': '#4b8d70',
    'status-glow': '#4b8d700e',
    'glass-border': '#ffffffcc',
    'floating-shadow': '#2929370c',
    'input-border': '#918b9d',
    placeholder: '#777381',
    'focus-glow': '#6d558c13',
    'selected-border': '#baa9d3',
    'selected-edge': '#8f7fa5',
    'accent-shadow': '#51436d14',
    'secondary-border': '#e1d8ee',
    'panel-border': '#e3dbef',
    'assistant-start': '#f0eaf9',
    'assistant-end': '#f8f5fc',
    'assistant-icon': '#e4daf2',
    'assistant-glass': '#ffffffa8',
    'assistant-input': '#bdb1cb',
    'assistant-button': '#c9bbdb',
    'ticket-arrow': '#a49cae',
    'ticket-divider': '#d7d1e1',
    'neutral-day': '#f2f3f4',
    'danger-border': '#e8b9ac',
    'success-border': '#c2d8c8',
    'result-border': '#b5a3cf',
    'empty-border': '#c6bed2',
    'calendar-border': '#d9cfea',
    'annual-border': '#d6cbe5',
    'annual-selected-border': '#c3b4d4',
    'annual-panel-border': '#e0d6ee',
    'annual-surface': '#faf8fe',
    'blocked-stripe': '#ead6c9',
    'blocked-surface': '#faf0e8',
    'surface-shadow': '#29293705',
    'scene-sky-start': '#e8e0fb',
    'scene-sky-end': '#f5eee9',
    'scene-water-start': '#9aadd0',
    'scene-water-end': '#d6d9f1',
    'scene-sun': '#f8be86',
    'scene-mountain-back': '#c2b4d8',
    'scene-mountain-front': '#9396b7',
    'scene-snow': '#f7f2fc',
    'scene-water-highlight': '#ecedf7',
    'scene-trees': '#555d7b',
    'scene-birds': '#7e7598',
  },
} as const
